### ISSUE TITLE
404 - https://huggingface.co/runwayml/stable-diffusion-inpainting/tree/main

### ISSUE THREAD

**Issue by johndpope** [Wangbenzhi/RealisHuman#2]

**Comment by johndpope** [comment]
is there suitable alternative- https://huggingface.co/models?search=stable-diffusion-inpainting ?


https://huggingface.co/benjamin-paine/stable-diffusion-v1-5-inpainting??

**Comment by Wangbenzhi** [comment]
> is there suitable alternative- https://huggingface.co/models?search=stable-diffusion-inpainting ?
> 
> https://huggingface.co/benjamin-paine/stable-diffusion-v1-5-inpainting??

yep, runway has run way. 
I have replaced the correct link in the README.
