### ISSUE TITLE
inference stage 1 error 

### ISSUE THREAD

**Issue by BugsMaker0513** [Wangbenzhi/RealisHuman#3]
RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]

**Comment by Wangbenzhi** [comment]
Please provide more detailed context information.

**Comment by BugsMaker0513** [comment]
用data下面的图片进行infer，输入命令：
CUDA_VISIBLE_DEVICES=0,1 torchrun --nnodes=1 --nproc_per_node=2 --master_port=6666 \
    inference_stage1.py \
    --config configs/stage1-hand.yaml \
    --output data/hand_example/hand_chip/repair \
    --ckpt checkpoint/stage1_hand/checkpoint-stage1-hand.ckpt


报错信息：
[rank1]:   File "/RealisHuman/realishuman/models/realishuman_unet.py", line 93, in forward
[rank1]:     encoder_hidden_states = self.clip_projector(encoder_hidden_states)
[rank1]: RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]
W0910 11:54:41.876000 140479334938432 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1456862 closing signal SIGTERM
E0910 11:54:43.194000 140479334938432 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 1456863) of binary

**Comment by Wangbenzhi** [comment]
Ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2".

**Comment by Wangbenzhi** [comment]
please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"

**Comment by Looperswag** [comment]
> please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"

Is it must be ckt.? safetensor format is acceptable?

**Comment by Wangbenzhi** [comment]
> > please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"
> 
> Is it must be ckt.? safetensor format is acceptable?

it's ok. You have the same issue?

**Comment by Looperswag** [comment]
![image](https://github.com/user-attachments/assets/d2609dc4-4d4e-4cc4-a078-fef0a11d7c00)
For the first part, I downloaded 1.5 model from another author on hugging face while it may need 'runway' version which has been declined 【https://huggingface.co/runwayml/stable-diffusion-v1-5】

For the second part, may be my data structure of pretrained model is wrong. COULD you please rectify it for me?
![image](https://github.com/user-attachments/assets/81bc7e3b-a3de-403e-8884-4c58e5ae707a)
![image](https://github.com/user-attachments/assets/8639c120-f8b7-49bb-b3c8-a47c11d32fc7)
![image](https://github.com/user-attachments/assets/3069395a-2f4b-4c84-b72a-8374c191c1b2)
![image](https://github.com/user-attachments/assets/8b2587ab-51dc-4a3b-b9cd-00d662df7958)

**Comment by Wangbenzhi** [comment]
> ![image](https://private-user-images.githubusercontent.com/62377702/366273216-d2609dc4-4d4e-4cc4-a078-fef0a11d7c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjUyNDksIm5iZiI6MTcyNjAyNDk0OSwicGF0aCI6Ii82MjM3NzcwMi8zNjYyNzMyMTYtZDI2MDlkYzQtNGQ0ZS00Y2M0LWEwNzgtZmVmMGExMWQ3YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NjMzM2JkMzQ4NzZhNzNhNGVmMjNmOGUyM2FiNjYzOWM1NjJiMTdjNjY0MmJkMWNkYWE5ZWM1ZDRiZWY2NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHqqnniJbnLMR5EW3NO_XKkq8WGcyyrKnWyYdbG-4-s) For the first part, I downloaded 1.5 model from another author on hugging face while it may need 'runway' version which has been declined 【[https://huggingface.co/runwayml/stable-diffusion-v1-5】](https://huggingface.co/runwayml/stable-diffusion-v1-5%E3%80%91)
> 
> For the second part, may be my data structure of pretrained model is wrong. COULD you please rectify it for me? ![image](https://private-user-images.githubusercontent.com/62377702/366273645-81bc7e3b-a3de-403e-8884-4c58e5ae707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjUyNDksIm5iZiI6MTcyNjAyNDk0OSwicGF0aCI6Ii82MjM3NzcwMi8zNjYyNzM2NDUtODFiYzdlM2ItYTNkZS00MDNlLTg4ODQtNGM1OGU1YWU3MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZDc4Mjg3M2JjZTY5MjE3ZWJkY2FhOTlhMTM4ZDQ2OGRiNWZhMTQ3MjNlZGYxNmIwMjg5ODMxNzJjMzBiNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7II87L4chu4eNMH4DaVDS45eYUvSFKjPx1EwAYMMqw8) ![image](https://private-user-images.githubusercontent.com/62377702/366273669-8639c120-f8b7-49bb-b3c8-a47c11d32fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjUyNDksIm5iZiI6MTcyNjAyNDk0OSwicGF0aCI6Ii82MjM3NzcwMi8zNjYyNzM2NjktODYzOWMxMjAtZjhiNy00OWJiLWIzYzgtYTQ3YzExZDMyZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNzYxZDQzMDQzNzNlZmUzMjBkOGExNzRiNTMxZGQ5NTg1YzM0ODQyZjMyZWFjODk1MjgwYzIyYTU2YjM1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDFiMR8pF-djKCbtN16MY7_D_sTjwN6-XH5OuuTPSfI) ![image](https://private-user-images.githubusercontent.com/62377702/366273697-3069395a-2f4b-4c84-b72a-8374c191c1b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjUyNDksIm5iZiI6MTcyNjAyNDk0OSwicGF0aCI6Ii82MjM3NzcwMi8zNjYyNzM2OTctMzA2OTM5NWEtMmY0Yi00Yzg0LWI3MmEtODM3NGMxOTFjMWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZmYwNzE0MTU3YWYzMjQ3Njk3MWVhYjg3NDI4MzY4ZWE4YzIxMWRhOWJjMGU3MDc1OTkyZjlhZjhhYmU2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YVIbBBNixorHUZ-7U19l7q_SrGCowYhOYPdt_BilA0w) ![image](https://private-user-images.githubusercontent.com/62377702/366273732-8b2587ab-51dc-4a3b-b9cd-00d662df7958.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjUyNDksIm5iZiI6MTcyNjAyNDk0OSwicGF0aCI6Ii82MjM3NzcwMi8zNjYyNzM3MzItOGIyNTg3YWItNTFkYy00YTNiLWI5Y2QtMDBkNjYyZGY3OTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAzMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNjQwYTU0MDg0NzA3ZWU4MzdkYmUzYmZlZjllMGY1Zjk0NWZkYmI1ZTNiYmNkMWFjYzY4NWFkZTIxMzg4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M9sDAIAAI-MiUfbwYPlxos6bDmkP1u_bLDqFSIY_I0k)

You should maintain the same directory structure as provided by hugging face and download the relevant files. For example,  in https://huggingface.co/facebook/dinov2-base/tree/main, it contains config.json and preprocessor_config.json. So, download them in your local dir.

**Comment by Looperswag** [comment]
I update the directory and still occurs:

![image](https://github.com/user-attachments/assets/ee510d83-3378-44d6-902d-19409540f94a)

**Comment by Looperswag** [comment]
> > > please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"
> > 
> > 
> > Is it must be ckt.? safetensor format is acceptable?
> 
> it's ok. You have the same issue?

After correct the directory and DINO files, I still have this issue:"RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[8, 257, 768]
E0911 12:26:53.127000 139982478788416 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 6265) of binary: /home/gin/miniconda3/envs/RealisHuman/bin/python"

**Comment by Wangbenzhi** [comment]
> > > > please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"
> > > 
> > > 
> > > Is it must be ckt.? safetensor format is acceptable?
> > 
> > 
> > it's ok. You have the same issue?
> 
> After correct the directory and DINO files, I still have this issue:"RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[8, 257, 768] E0911 12:26:53.127000 139982478788416 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 6265) of binary: /home/gin/miniconda3/envs/RealisHuman/bin/python"


thanks for your reply, i will check it.

**Comment by Wangbenzhi** [comment]
> self.clip_projector(encoder_hidden_states)

I have checked that there is no problem, please make sure that the DINOv2 model is correctly prepared according to the config yaml.

**Comment by BugsMaker0513** [comment]
Anyone success?

**Comment by BugsMaker0513** [comment]
> > > > please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"
> > > 
> > > 
> > > Is it must be ckt.? safetensor format is acceptable?
> > 
> > 
> > it's ok. You have the same issue?
> 
> After correct the directory and DINO files, I still have this issue:"RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[8, 257, 768] E0911 12:26:53.127000 139982478788416 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 6265) of binary: /home/gin/miniconda3/envs/RealisHuman/bin/python"

Hello, did you solve the problem?

**Comment by Looperswag** [comment]
> > > > > please ensure that the correct DINOv2 checkpoints are located in the path "pretrained_models/DINO/dinov2"
> > > > 
> > > > 
> > > > Is it must be ckt.? safetensor format is acceptable?
> > > 
> > > 
> > > it's ok. You have the same issue?
> > 
> > 
> > After correct the directory and DINO files, I still have this issue:"RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[8, 257, 768] E0911 12:26:53.127000 139982478788416 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 6265) of binary: /home/gin/miniconda3/envs/RealisHuman/bin/python"
> 
> Hello, did you solve the problem?

yep. you need download all the files on the official document. I just download the ckt/safetensor at the first place.

**Comment by BugsMaker0513** [comment]
> > self.clip_projector(encoder_hidden_states)
> 
> I have checked that there is no problem, please make sure that the DINOv2 model is correctly prepared according to the config yaml.

In "RealisHuman/pretrained_models/dinov2-base/config.json", line9,  there is "hidden_size": 768.
But, the error is :
       File "RealisHuman/realishuman/models/realishuman_unet.py", line 93, in forward
       [rank1]:     encoder_hidden_states = self.clip_projector(encoder_hidden_states)
       RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]

So, I think it is not the problem of DINO files ?

**Comment by Looperswag** [comment]
> > > self.clip_projector(encoder_hidden_states)
> > 
> > 
> > I have checked that there is no problem, please make sure that the DINOv2 model is correctly prepared according to the config yaml.
> 
> In "RealisHuman/pretrained_models/dinov2-base/config.json", line9, there is "hidden_size": 768. But, the error is : File "RealisHuman/realishuman/models/realishuman_unet.py", line 93, in forward [rank1]: encoder_hidden_states = self.clip_projector(encoder_hidden_states) RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]
> 
> So, I think it is not the problem of DINO files ?

Oh right. I stucked here for a while. And I solved it by replacing all the files from DINOv2 base to DINOv2 large. cc: https://huggingface.co/facebook/dinov2-large/tree/main
It will solve the dimension problems

**Comment by BugsMaker0513** [comment]
> > > > self.clip_projector(encoder_hidden_states)
> > > 
> > > 
> > > I have checked that there is no problem, please make sure that the DINOv2 model is correctly prepared according to the config yaml.
> > 
> > 
> > In "RealisHuman/pretrained_models/dinov2-base/config.json", line9, there is "hidden_size": 768. But, the error is : File "RealisHuman/realishuman/models/realishuman_unet.py", line 93, in forward [rank1]: encoder_hidden_states = self.clip_projector(encoder_hidden_states) RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]
> > So, I think it is not the problem of DINO files ?
> 
> Oh right. I stucked here for a while. And I solved it by replacing all the files from DINOv2 base to DINOv2 large. cc: https://huggingface.co/facebook/dinov2-large/tree/main It will solve the dimension problems

thanks a lot!!

**Comment by Wangbenzhi** [comment]
> > > > self.clip_projector(encoder_hidden_states)
> > > 
> > > 
> > > I have checked that there is no problem, please make sure that the DINOv2 model is correctly prepared according to the config yaml.
> > 
> > 
> > In "RealisHuman/pretrained_models/dinov2-base/config.json", line9, there is "hidden_size": 768. But, the error is : File "RealisHuman/realishuman/models/realishuman_unet.py", line 93, in forward [rank1]: encoder_hidden_states = self.clip_projector(encoder_hidden_states) RuntimeError: Given normalized_shape=[1024], expected input with shape [*, 1024], but got input of size[4, 257, 768]
> > So, I think it is not the problem of DINO files ?
> 
> Oh right. I stucked here for a while. And I solved it by replacing all the files from DINOv2 base to DINOv2 large. cc: https://huggingface.co/facebook/dinov2-large/tree/main It will solve the dimension problems

fixed.
