### ISSUE TITLE
Multi-person issue

### ISSUE THREAD

**Issue by Looperswag** [Wangbenzhi/RealisHuman#5]
What if my image has more than 1 people. I run the 3ddfa, dwpose, hamer and your code can only detect a pair of hands (or one head).

**Comment by Wangbenzhi** [comment]
RealisHuman DONOT support multi-person yet.

**Comment by Looperswag** [comment]
Thx for the reply, an additional question:

For personal training process, the training data should be all regular human parts image or regular mix with counterfeit image. If it is the second one, what is the proportion of the regular and counterfeit?

**Comment by Wangbenzhi** [comment]
For details on the training process, please refer to the data preparation subsection of the paper.
