### ISSUE TITLE
HAMER has no file named "demo_image.py"

### ISSUE THREAD

**Issue by BugsMaker0513** [Wangbenzhi/RealisHuman#6]
python demo_image.py --img_folder {PATH_TO_IMAGE_DIR}/image --out_folder {PATH_TO_SAVE_HAMER}/hamer --full_frame

HAMER里只有demo.py，而且输出的图片是crop后的手部，不是全图的3d手。能否上传一下demo_image.py？

**Comment by Wangbenzhi** [comment]
please use the code in RealisHuman/submodules/hamer-main
