### ISSUE TITLE
阶段一通过了，但阶段二执行异常 "cross_attention_dim must be specified for CrossAttnDownBlock2D")

### ISSUE THREAD

**Issue by a1123622944** [Wangbenzhi/RealisHuman#9]
]
6s
!CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node=1 \
    inference_stage2.py --config configs/stage2-hand.yaml --output data/hand_example/hand_chip/inpaint \
    --ckpt checkpoint/stage2_hand/checkpoint-stage2-hand.ckpt
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
/usr/local/lib/python3.10/dist-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  torch.utils._pytree._register_pytree_node(
09/30/2024 06:51:24 - INFO - root - Load scheduler, tokenizer and models.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/content/RealisHuman/inference_stage2.py", line 280, in <module>
[rank0]:     main(launcher=args.launcher, sanity_check_during_validation=args.sanity_check_during_validation,
[rank0]:   File "/content/RealisHuman/inference_stage2.py", line 121, in main
[rank0]:     vae = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae")
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_utils.py", line 795, in from_pretrained
[rank0]:     model = cls.from_config(config, **unused_kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 259, in from_config
[rank0]:     model = cls(**init_dict)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 649, in inner_init
[rank0]:     init(self, *args, **init_kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 88, in __init__
[rank0]:     self.encoder = Encoder(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/autoencoders/vae.py", line 103, in __init__
[rank0]:     down_block = get_down_block(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_blocks.py", line 119, in get_down_block
[rank0]:     raise ValueError("cross_attention_dim must be specified for CrossAttnDownBlock2D")
[rank0]: ValueError: cross_attention_dim must be specified for CrossAttnDownBlock2D
E0930 06:51:25.450000 136206980706944 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 9788) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by Wangbenzhi** [comment]
please refer the issue in diffuser. https://github.com/huggingface/diffusers/issues/5693
